import Head from "next/head";
import Banner from "../src/components/Banner";
import Feed from "../src/components/Feed";
import Navbar from "../src/components/Navbar";

export default function Home(props) {
  return (
    <div className="bg-gray-200">
      <Head>
        <title>Amazon 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="max-w-screen-2xl mx-auto">
        <Banner />
        <Feed products={props.products} />
      </main>
    </div>
  );
}

const dev = process.env.NODE_ENV !== "production";

export const server = dev
  ? "https://fakestoreapi.com/products"
  : "https://fakestoreapi.com/products";

export async function getServerSideProps() {
  const response = await fetch(`${server}`, {
    method: "GET",
  });
  const products = await response.json();
  return {
    props: {
      products,
    },
  };
}

// https://fakestoreapi.com/products
